### PR TITLE
feat: add cgroup v2 support for metrics

### LINKED ISSUE #162: `stats` doesn't work on cgroup v2
When I ran `ctr task metric <task-name>`, the container runtime returns a rpc error, indicating that the metric collecting method doesn't work on cgroup v2. I think I know the issue lies in the `collect_metric` method. Will have a PR to fix it. 

### Reproduce

```
➜  rust-extensions-fork git:(main) sudo ctr run --net-host --rm --runtime=io.containerd.runc.v2-rs docker.io/library/py-flask-app:latest pyflask
 * Serving Flask app 'app'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8000
 * Running on http://10.0.0.4:8000
Press CTRL+C to quit
ctr: rpc error: code = Unknown desc = ttrpc: closed: unknown
```

```
➜  runwasi git:(issue64) ✗ sudo ctr task metric pyflask         
ctr: not found
```

### PR DESCRIPTION
**Pull request by Mossaka**
This commits adds cgroup v2 support for collecting metrics in the shim.

Additionally, it uses CPU controller instead of the CPUAcct controller
for reporting CPU metrics back to `containerd`.

Closes #162

### CODE REVIEW

**Comment by mxpv** [comment]
This PR includes changes from https://github.com/containerd/rust-extensions/pull/161
Could you pls rebase this PR against `main` branch?

**Comment by Mossaka** [comment]
> Could you pls rebase this PR against main branch?

Absolutely. Done :)

**Comment by jsturtevant** [comment]
LGTM

Would it be worth adding `ubuntu 22.04` to https://github.com/containerd/rust-extensions/blob/27a503a474c68cdba7eff5b9f1b439d1846c39e0/.github/workflows/ci.yml#L96  I believe 22.04 has cgroupv2 by default so that would add some coverage? Maybe in a follow up incase there are other issues?

**Review by mxpv — APPROVED** [review]

**Comment by Mossaka** [comment]
Could we merge this? @mxpv

**Comment by mxpv** [comment]
Done!

**Pull request merged**
