### PR TITLE
.github/workflows/ci: add machete to CI

### PR DESCRIPTION
**Pull request by Mossaka**
this will check if there are unused deps in this repo

### CODE REVIEW

**Comment by mxpv** [comment]
Try rebase?

**Comment by Mossaka** [comment]
Ah the issue was not about rebase. The error from `cargo machete` says

```bash
containerd-snapshots -- ./crates/snapshots/Cargo.toml:
	prost
containerd-client -- ./crates/client/Cargo.toml:
	prost
```

we probably want to ignore `prost` dependency as it's actually being used.

**Review by mxpv — APPROVED** [review]

**Comment by Mossaka** [comment]
Can we merge this PR? @mxpv

**Comment by mxpv** [comment]
@Mossaka could you pls rebase against latest `main`? Looks like there is a CI issue that needs to be addressed first.

**Comment by Mossaka** [comment]
Looks like I need to rebase this one

**Pull request merged**
