### PR TITLE
The golang "true" is 0 ,but Rust "true" is 1

### PR DESCRIPTION
**Pull request by jokemanfire**
The int variable value of the bool variable in Golang language is different from that of rust。
In golang 
// bool is the set of boolean values, true and false.
type bool bool

// true and false are the two untyped boolean values.
const (
	true  = 0 == 0 // Untyped bool.
	false = 0 != 0 // Untyped bool.
)

### CODE REVIEW

**Comment by mxpv** [comment]
I'm not sure I understand this.
`KillRequest` is protobuf generated structure and boolean `all` field.
Where do you see it inverted?

**Comment by jokemanfire** [comment]
In 'task.rs' kill function  ,    there is    "  info!("Kill request for {:?}", req);"     this way can print result .     but when you send the KillRequest in containerd , 
when ctr set all "true"   but shim get false ,  I find it in test function "TestContainerDrainExecIOAfterExit " ， Maybe I was wrong, But I feel confused , ctr send true ，but shim get false . so I think golang deal with bool  "0" represent true .

**Comment by Burning1020** [comment]
Can you provide more defails, such as the log msg of `info!("Kill request for {:?}", req);`? It has a long way between `ctr` and `task.kill()`, I think it is not a bug of rust shim.

**Comment by jokemanfire** [comment]
this is containerd's problem I will bring issus  to containerd

**Pull request closed without merging**
