### PR TITLE
Re-enable TaskResize test in CI

### PR DESCRIPTION
**Pull request by jsturtevant**
Testing the failing tests in local environment for #122  I found this test passes.  Trying it in CI.

### CODE REVIEW

**Review by Burning1020 — COMMENTED** [review]
These tests occurred by chance. May need to run it several times to potentially replicate the the problem.

**Comment by jsturtevant** [comment]
interesting, I ran this specific tests a bunch of times locally but I will see if I can reproduce running in a loop locally.  I don't ability to re-trigger the jobs here so might do that on my branch as well.

**Comment by jsturtevant** [comment]
I ran this single, specific test 100 times successfully. Will try a few more times and also try in CI with all the tests running incase its a issue when running with everything:

```
=== RUN   TestTaskResize
=== PAUSE TestTaskResize
=== CONT  TestTaskResize
--- PASS: TestTaskResize (1.10s)
ok      github.com/containerd/containerd/integration/client     2.704s
make integration completed successfully for 100 attempts.
```

**Comment by jsturtevant** [comment]
I got it on the 190th run locally:

```
INFO[0000] start to pull seed image                      image="ghcr.io/containerd/busybox:1.32"
=== RUN   TestTaskResize
=== PAUSE TestTaskResize
=== CONT  TestTaskResize
    container_test.go:2357: failed to create shim task: ttrpc: closed: unknown
```

**Comment by jsturtevant** [comment]
Needs more investigation, I tried it with the fix that went into ttrpc (https://github.com/containerd/ttrpc-rust/pull/208) but it didn't help. I've added a note to #122 

/close

**Pull request closed without merging**
