### PR TITLE
Remove sync code from runc shim

### PR DESCRIPTION
**Pull request by mxpv**
Closes: https://github.com/containerd/rust-extensions/issues/134

### CODE REVIEW

**Comment by mxpv** [comment]
@jsturtevant any ideas why windows integration tests fail? Not sure I get what exactly wrong with it and I don't have windows env to verify (this also fails in `main`).

```
error[E0432]: unresolved import `ttrpc::asynchronous`
  --> crates\shim-protos\src\lib.rs:93:20
   |
93 |     pub use ttrpc::asynchronous::Client;
   |                    ^^^^^^^^^^^^ could not find `asynchronous` in `ttrpc`
```

**Comment by jsturtevant** [comment]
looks like bringing in the `async` feature somehow. I will take a look today. 

> this also fails in main

Looks like main is failing due to https://github.com/containerd/rust-extensions/issues/160?

**Comment by mxpv** [comment]
Let me rebase this and give it another try.

**Comment by jsturtevant** [comment]
rebase didn't help 😞.  

CI on main is passing today: https://github.com/containerd/rust-extensions/actions/runs/5743079375 and I was able to run the integration test locally on main. Going to pull this PR to see I can track down what is causing the mix up

**Comment by jsturtevant** [comment]
Still tracking down what is happening but `cargo build -p containerd-shim-protos` and `cargo build -p containerd-shim` builds fine on windows.

but `cargo build --example skeleton` fails with message `error: could not compile containerd-shim-protos (lib) due to 117 previous error`

**Comment by jsturtevant** [comment]
@mxpv I don't know why but it seems the examples are getting the `feature=async` enabled on them after the changes in this PR.  Maybe the changes in the `runc crate` are causing the compiler/cargo to pick that up by default?

If I run `cargo build --example skeleton -p containerd-shim` then this works.  So the fix would be to add `-p containerd-shim` to the cargo calls in:

https://github.com/containerd/rust-extensions/blob/27a503a474c68cdba7eff5b9f1b439d1846c39e0/.github/workflows/ci-windows.yml#L97-L99

**Comment by mxpv** [comment]
@jsturtevant That did the trick!

**Comment by jsturtevant** [comment]
LGTM

**Pull request merged**
